# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JjStacked < Formula
  desc "Stacked pull requests for Jujutsu users"
  homepage "https://github.com/OSMorph/jj-stacked"
  version "2.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OSMorph/jj-stacked/releases/download/v2.5.1/jj-stacked_2.5.1_darwin_amd64.tar.gz"
      sha256 "7deebb16b39ba872b79921b1f6c05562d7de29e20fa7765c69d22360d5a62cbf"

      define_method(:install) do
        bin.install "jj-stacked"
        bin.install "jjk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OSMorph/jj-stacked/releases/download/v2.5.1/jj-stacked_2.5.1_darwin_arm64.tar.gz"
      sha256 "e377751f0f80264f82cb4dc80fd08b355546fb7b0040ea33f53bc7396250b0d1"

      define_method(:install) do
        bin.install "jj-stacked"
        bin.install "jjk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OSMorph/jj-stacked/releases/download/v2.5.1/jj-stacked_2.5.1_linux_amd64.tar.gz"
      sha256 "94d95ea5d2a461cdbcde14b427b2c0125a5d25ad3e65ba88f31e31f2e43c6d4a"
      define_method(:install) do
        bin.install "jj-stacked"
        bin.install "jjk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OSMorph/jj-stacked/releases/download/v2.5.1/jj-stacked_2.5.1_linux_arm64.tar.gz"
      sha256 "051fa339e1a2dc5b9ecf7826d00b7bf57dba7e313865eabd380d02d1edbd70e5"
      define_method(:install) do
        bin.install "jj-stacked"
        bin.install "jjk"
      end
    end
  end

  test do
    system "#{bin}/jj-stacked", "--version"
  end
end
